# Using https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# test trpc endpoints

@hostname = https://krx4zd3cku3zrcizhave745fg40nvdme.lambda-url.us-east-1.on.aws
# @hostname = https://5stufiwjink2ilejxzelc43niu0gjcbl.lambda-url.us-east-1.on.aws/
@sessionId = 9d80dd67-ffae-40dc-b899-f56d84dd4af0

GET {{hostname}}/user.nonce HTTP/1.1
content-type: application/json

###

POST {{hostname}}/user.signIn HTTP/1.1
content-type: application/json

{
  "signature": "0xa9bb959540f5733294d8ff7899ab8e9492564b0636e189c6af99d2f8b2341a331022a2b85cc5eb73d867ece9e45a7a9015250d2c51d39ee32e8425c7ddd9c20b1c",
  "message": {
    "domain": "1.x.wagmi.sh",
    "address": "0x50099BED7fD2b7Ca7000c8A87d6b2ED83971E363",
    "statement": "Sign in with Ethereum to the app.",
    "uri": "https://1.x.wagmi.sh",
    "version": "1",
    "chainId": 1,
    "nonce": "uVOj37LwbFuHk5JMU",
    "issuedAt": "2024-09-17T02:22:16.473Z"
  },
  "nonce": "uVOj37LwbFuHk5JMU",
  "username": "rorhug",
  "email": "rorhug@gmail.com"
}


### Create a post

POST {{hostname}}/post.create HTTP/1.1
content-type: application/json
X-Session-Id: {{sessionId}}

{
  "title": "My 11 post",
  "content": "This is the content of my 10 post"
}

### Get all posts

GET {{hostname}}/post.getAll HTTP/1.1
content-type: application/json

### follow self - error

POST {{hostname}}/follows.follow HTTP/1.1
content-type: application/json
X-Session-Id: {{sessionId}}

{
  "followedAddress": "0x50099BED7fD2b7Ca7000c8A87d6b2ED83971E363"
}

### follow user

POST {{hostname}}/follows.follow HTTP/1.1
content-type: application/json
X-Session-Id: {{sessionId}}

{
  "followedAddress": "0x40088BED7fD2b7Ca7000c8A87d6b2ED83971E399"
}

### unfollow user

POST {{hostname}}/follows.unfollow HTTP/1.1
content-type: application/json
X-Session-Id: {{sessionId}}

{
  "followedAddress": "0x40088BED7fD2b7Ca7000c8A87d6b2ED83971E399"
}

### get followers

GET {{hostname}}/follows.getFollowers HTTP/1.1
content-type: application/json
X-Session-Id: {{sessionId}}

### search posts
GET {{hostname}}/post.search#?authorAddress=0x50099BED7fD2b7Ca7000c8A87d6b2ED83971E363&titleContains=post HTTP/1.1
content-type: application/json
X-Session-Id: {{sessionId}}