/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "BlogPostEmailQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "BlogPostNotificationDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "BlogPostNotificationQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MyPostgres": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Postgres"
      "username": string
    }
    "Trpc": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
